In [6]:
from helpers import read_results
import pandas as pd

In [14]:
hyperparams_rows = []
for fold in range(10):
    results = read_results('BEDL', 'SJAFFE', fold)
    results['hyperparameters']
    kl_div = results['val_kl_divergence']
    hyperparams_rows.append({"fold": fold, "kl_divergence": kl_div, **results["hyperparameters"]})

hyperparams_df = pd.DataFrame(hyperparams_rows)
hyperparams_df.sort_values("kl_divergence")

,fold,kl_divergence,batch_size,dropout_rate,learning_rate,max_epochs,minimum,n_hidden,n_latent,patience,weight_decay
6,6,0.036748,32,0.2,0.0100,2500,100,128,16,100,0.00001
3,3,0.039794,32,0.0,0.0100,2500,100,128,16,100,0.01000
7,7,0.042310,32,0.0,0.0100,2500,100,16,16,100,0.00100
4,4,0.042882,32,0.2,0.0100,2500,100,128,16,100,0.01000
0,0,0.043447,32,0.0,0.0100,2500,100,16,16,100,0.01000
5,5,0.044725,128,0.2,0.0100,2500,100,128,16,100,0.00100
2,2,0.044954,32,0.2,0.0100,2500,100,128,16,100,0.00100
1,1,0.050812,128,0.4,0.0100,2500,100,128,16,100,0.00010
8,8,0.079887,128,0.0,0.0100,2500,100,128,16,100,0.00001
9,9,0.081466,32,0.0,0.0001,2500,100,128,16,100,0.00001

In [15]:
hyperparams_rows = []
for fold in range(10):
    results = read_results('BEDL_BAYES', 'SJAFFE', fold)
    results['hyperparameters']
    kl_div = results['val_kl_divergence']
    hyperparams_rows.append({"fold": fold, "kl_divergence": kl_div, **results["hyperparameters"]})

hyperparams_df = pd.DataFrame(hyperparams_rows)
hyperparams_df.sort_values("kl_divergence")

,fold,kl_divergence,batch_size,dropout_rate,learning_rate,max_epochs,minimum,n_hidden,n_latent,patience,weight_decay
3,3,0.036716,32,0.4,0.0100,2500,100,128,16,100,0.00100
7,7,0.038496,32,0.2,0.0100,2500,100,64,16,100,0.00010
6,6,0.039016,64,0.4,0.0100,2500,100,128,16,100,0.01000
4,4,0.044578,32,0.2,0.0100,2500,100,128,16,100,0.01000
5,5,0.044975,32,0.4,0.0100,2500,100,16,16,100,0.00100
1,1,0.045369,32,0.0,0.0100,2500,100,128,16,100,0.01000
0,0,0.046055,32,0.4,0.0100,2500,100,4,16,100,0.01000
2,2,0.046128,64,0.4,0.0100,2500,100,128,16,100,0.00100
9,9,0.048431,64,0.2,0.0100,2500,100,128,16,100,0.01000
8,8,0.063221,32,0.2,0.0001,2500,100,128,16,100,0.00001

In [16]:
hyperparams_rows = []
for fold in range(10):
    results = read_results('EDL', 'SJAFFE', fold)
    results['hyperparameters']
    kl_div = results['val_kl_divergence']
    hyperparams_rows.append({"fold": fold, "kl_divergence": kl_div, **results["hyperparameters"]})

hyperparams_df = pd.DataFrame(hyperparams_rows)
hyperparams_df.sort_values("kl_divergence")

,fold,kl_divergence,batch_size,dropout_rate,learning_rate,max_epochs,minimum,n_hidden,n_latent,patience,weight_decay
3,3,0.035157,32,0.2,0.0100,2500,100,64,16,100,0.00001
6,6,0.038374,32,0.4,0.0100,2500,100,128,16,100,0.00010
0,0,0.041186,128,0.2,0.0100,2500,100,64,16,100,0.00010
5,5,0.044598,64,0.2,0.0100,2500,100,128,16,100,0.00100
4,4,0.048308,32,0.0,0.0100,2500,100,128,16,100,0.00100
2,2,0.050954,64,0.2,0.0100,2500,100,64,16,100,0.01000
8,8,0.074230,32,0.2,0.0100,2500,100,16,16,100,0.00100
1,1,0.078881,32,0.2,0.0001,2500,100,4,16,100,0.00001
7,7,0.080997,128,0.0,0.0010,2500,100,4,16,100,0.01000
9,9,0.082932,128,0.2,0.0001,2500,100,128,16,100,0.00010

In [17]:
hyperparams_rows = []
for fold in range(10):
    results = read_results('EDL_BAYES', 'SJAFFE', fold)
    results['hyperparameters']
    kl_div = results['val_kl_divergence']
    hyperparams_rows.append({"fold": fold, "kl_divergence": kl_div, **results["hyperparameters"]})

hyperparams_df = pd.DataFrame(hyperparams_rows)
hyperparams_df.sort_values("kl_divergence")

,fold,kl_divergence,batch_size,dropout_rate,learning_rate,max_epochs,minimum,n_hidden,n_latent,patience,weight_decay
4,4,0.068764,32,0.0,0.0010,2500,100,16,16,100,0.01000
5,5,0.069776,64,0.2,0.0010,2500,100,16,16,100,0.00100
3,3,0.069853,32,0.0,0.0100,2500,100,16,16,100,0.01000
0,0,0.071765,128,0.0,0.0100,2500,100,128,16,100,0.00001
8,8,0.074134,32,0.4,0.0100,2500,100,4,16,100,0.01000
6,6,0.076051,64,0.0,0.0001,2500,100,128,16,100,0.00010
1,1,0.078034,32,0.2,0.0010,2500,100,64,16,100,0.00001
7,7,0.079943,32,0.0,0.0001,2500,100,4,16,100,0.00100
9,9,0.080988,64,0.0,0.0010,2500,100,4,16,100,0.01000
2,2,0.081033,64,0.2,0.0001,2500,100,16,16,100,0.00100